# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/lukas/PycharmProjects/zd_inventory/ui/zd_equipment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlg_equipment(object):
    def setupUi(self, dlg_equipment):
        dlg_equipment.setObjectName("dlg_equipment")
        dlg_equipment.resize(295, 117)
        self.formLayoutWidget = QtWidgets.QWidget(dlg_equipment)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 105))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 20)
        self.formLayout.setObjectName("formLayout")
        self.lbl_equip = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_equip.setText("")
        self.lbl_equip.setObjectName("lbl_equip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_equip)
        self.led_equip = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_equip.sizePolicy().hasHeightForWidth())
        self.led_equip.setSizePolicy(sizePolicy)
        self.led_equip.setObjectName("led_equip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.led_equip)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_save.setEnabled(False)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.lbl_error = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_error)

        self.retranslateUi(dlg_equipment)
        QtCore.QMetaObject.connectSlotsByName(dlg_equipment)

    def retranslateUi(self, dlg_equipment):
        _translate = QtCore.QCoreApplication.translate
        dlg_equipment.setWindowTitle(_translate("dlg_equipment", "Dialog"))
        self.btn_save.setText(_translate("dlg_equipment", "Zapisz"))
        self.btn_cancel.setText(_translate("dlg_equipment", "Anuluj"))
