# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/lukas/PycharmProjects/zd_inventory/ui/zd_tags_return.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zd_tags_return(object):
    def setupUi(self, zd_tags_return):
        zd_tags_return.setObjectName("zd_tags_return")
        zd_tags_return.resize(375, 125)
        self.layoutWidget = QtWidgets.QWidget(zd_tags_return)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 371, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.led_from = QtWidgets.QLineEdit(self.layoutWidget)
        self.led_from.setEnabled(True)
        self.led_from.setObjectName("led_from")
        self.horizontalLayout_4.addWidget(self.led_from)
        self.led_to = QtWidgets.QLineEdit(self.layoutWidget)
        self.led_to.setEnabled(True)
        self.led_to.setObjectName("led_to")
        self.horizontalLayout_4.addWidget(self.led_to)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.lbl_error = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")
        self.verticalLayout_2.addWidget(self.lbl_error)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_tag = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_add_tag.setEnabled(False)
        self.btn_add_tag.setObjectName("btn_add_tag")
        self.horizontalLayout_2.addWidget(self.btn_add_tag)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 4)

        self.retranslateUi(zd_tags_return)
        QtCore.QMetaObject.connectSlotsByName(zd_tags_return)

    def retranslateUi(self, zd_tags_return):
        _translate = QtCore.QCoreApplication.translate
        zd_tags_return.setWindowTitle(_translate("zd_tags_return", "Dialog"))
        self.led_from.setPlaceholderText(_translate("zd_tags_return", "Numery od"))
        self.led_to.setPlaceholderText(_translate("zd_tags_return", "Numery do"))
        self.btn_add_tag.setText(_translate("zd_tags_return", "Zapisz"))
